# -*- coding: utf-8 -*-
"""image_simillarity

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ppu9e9yd6Fvy1Fk9cVFXkAN7-Unce4Qb
"""

import cv2
import numpy as np
import matplotlib.pylab as plt

image1 = plt.imread('/content/바다_1.jpeg')
image2 = plt.imread('/content/바다_2.jpg')
image3 = plt.imread('/content/P_SG-KOMPSAT-2_93.jpg')

# 서브플롯 생성
plt.figure(figsize=(15, 5))

# 첫 번째 서브플롯
plt.subplot(1, 3, 1)
plt.imshow(image1)
plt.title('Image 1')

# 두 번째 서브플롯
plt.subplot(1, 3, 2)
plt.imshow(image2)
plt.title('Image 2')

# 세 번째 서브플롯
plt.subplot(1, 3, 3)
plt.imshow(image3)
plt.title('Image 3')

# 레이아웃 조정
plt.tight_layout()

# 그래프 표시
plt.show()

"""1. 유사도 계산 바다-바다"""

imgs = []
imgs.append(cv2.resize(cv2.imread('/content/바다_1.jpeg'),(256,256)))
imgs.append(cv2.resize(cv2.imread('/content/바다_2.jpg'),(256,256)))


hists = []
for img in imgs:
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hist = cv2.calcHist([hsv], [0], None, [256], [0, 256])
    cv2.normalize(hist, hist, 0, 1, cv2.NORM_MINMAX)
    hists.append(hist)

query = hists[0]

methods = ['CORREL', 'CHISQR', 'INTERSECT', 'BHATTACHARYYA']

for index, name in enumerate(methods):
    print('%-10s' % name, end = '\t')

    for i, histogram in enumerate(hists):
        ret = cv2.compareHist(query ,histogram, index)

        print("img%d :%7.2f"% (i+1 , ret), end='\t')

    print()

"""2. 유사도 계산 바다-위성사진"""

imgs = []
imgs.append(cv2.resize(cv2.imread('/content/바다_1.jpeg'),(256,256)))
imgs.append(cv2.resize(cv2.imread('/content/P_SG-KOMPSAT-2_93.jpg'),(256,256)))


hists = []
for img in imgs:
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hist = cv2.calcHist([hsv], [0], None, [256], [0, 256])
    cv2.normalize(hist, hist, 0, 1, cv2.NORM_MINMAX)
    hists.append(hist)

query = hists[0]

methods = ['CORREL', 'CHISQR', 'INTERSECT', 'BHATTACHARYYA']

for index, name in enumerate(methods):
    print('%-10s' % name, end = '\t')

    for i, histogram in enumerate(hists):
        ret = cv2.compareHist(query ,histogram, index)

        print("img%d :%7.2f"% (i+1 , ret), end='\t')

    print()

